export enum ENVIRONMENT_TYPE {
  POPUP = 0,
  NOTIFICATION,
  FULLSCREEN,
  BACKGROUND,
}

export const PAGE_TYPE = {
  POPUP: 'popup',
  HOME: 'home',
  NOTIFICATION: 'notification',
};

export const MESSAGE_TYPE = {
  WORKER_KEEP_ALIVE_MESSAGE: 'WORKER_KEEP_ALIVE_MESSAGE',
  ACK_KEEP_ALIVE_MESSAGE: 'ACK_KEEP_ALIVE_MESSAGE',
  UPDATE_STORE_DATA: 'UPDATE_STORE_DATA',
  ONBOARDING_COMPLETE: 'ONBOARDING_COMPLETE',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
};
